#
# Copyright (C) 2020-2024 Lin Song <linsongui@gmail.com>
#
# This work is licensed under the Creative Commons Attribution-ShareAlike 3.0
# Unported License: http://creativecommons.org/licenses/by-sa/3.0/
#
# Attribution required: please include my name in any derivative and let me
# know how you have improved it!

name: build

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - '.github/workflows/main-alpine.yml'
      - '.github/workflows/buildx.yml'
      - '.github/workflows/shellcheck.yml'
      - '.github/workflows/vpn_test.yml'
      - '.dockerignore'
      - 'Dockerfile'
      - 'run.sh'

jobs:
  shellcheck:
    uses: ./.github/workflows/shellcheck.yml

  vpn_test:
    uses: ./.github/workflows/vpn_test.yml
    with:
      os_type: alpine
